name: Apply PR Template

on:
  pull_request:
    types: [opened, edited]

jobs:
  apply-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Extract ticket number from branch name
        id: extract_ticket
        run: |
          # Extract the ticket number from the branch name
          TICKET_NUMBER=$(echo "${GITHUB_REF##*/}" | sed -E 's/.*([A-Z]+-[0-9]+).*/\1/')
          
          # If no ticket number is found, set a default or handle error
          if [ -z "$TICKET_NUMBER" ]; then
            echo "No ticket number found in the branch name. Skipping this step."
            TICKET_NUMBER="N/A"  # Set to a default value or exit with an error
          fi

          echo "TICKET_NUMBER=$TICKET_NUMBER" >> $GITHUB_ENV

      - name: Add comment to PR with template content
        run: |
          PR_DESCRIPTION=$(cat .github/PULL_REQUEST_TEMPLATE/uc_branch_template.md | sed "s/{{TICKET_NUMBER}}/${{ env.TICKET_NUMBER }}/g")
          echo "Template Content:"
          echo "$PR_DESCRIPTION"
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"$PR_DESCRIPTION\"}" \
          "${{ github.event.pull_request._links.comments.href }}"
