name: pr label
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  pr-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: agaroot-technologies/action-restrict-pr-label@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules: |            
            main <- develop [release]
            develop <- project/* [ignore]
